#!/usr/bin/env bash

# Description: Making our container working infinitely.
# Arsenii Gorkin <gorkin@protonmail.com>

/etc/init.d/apache2 start

#Starting Bash for managing the system from command line
bash
